// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqsDjQscXIbzPOHqK54cDWei5B86XDIw',
    appId: '1:438708720641:web:8f6e74f8ad5ebb4a635c00',
    messagingSenderId: '438708720641',
    projectId: 'whatsapp-web-clone-9eac6',
    authDomain: 'whatsapp-web-clone-9eac6.firebaseapp.com',
    storageBucket: 'whatsapp-web-clone-9eac6.appspot.com',
    measurementId: 'G-WELMGLW8B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vPT7kA4HyhFieaOiIIt2AP0zfN8IjUE',
    appId: '1:438708720641:android:8867256ead64151d635c00',
    messagingSenderId: '438708720641',
    projectId: 'whatsapp-web-clone-9eac6',
    storageBucket: 'whatsapp-web-clone-9eac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMy1XT1w2BwYnPRQ3CTErDejKKNooiBFU',
    appId: '1:438708720641:ios:0ad14afd5c0cd4aa635c00',
    messagingSenderId: '438708720641',
    projectId: 'whatsapp-web-clone-9eac6',
    storageBucket: 'whatsapp-web-clone-9eac6.appspot.com',
    iosClientId: '438708720641-hap5kuo7edhaj5836u40b4f02g4af3t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
